#!/bin/bash
# 빠른 배포 스크립트

echo "🚀 AsKNU Backend - Render 배포 가이드"
echo "======================================"
echo ""

# 현재 상태 확인
echo "📊 1. 현재 상태"
echo "   브랜치: $(git branch --show-current)"
echo "   최근 커밋: $(git log --oneline -1)"
echo ""

# GitHub 푸시
echo "📤 2. GitHub에 푸시"
echo "   명령어: git push origin $(git branch --show-current)"
read -p "   지금 푸시하시겠습니까? (y/n): " push_confirm
if [ "$push_confirm" = "y" ]; then
    git push origin $(git branch --show-current)
    echo "   ✅ 푸시 완료!"
else
    echo "   ⏭️  건너뛰기"
fi
echo ""

# Render 배포 안내
echo "🌐 3. Render 배포 단계"
echo "======================================"
echo ""
echo "Step 1: Render 접속"
echo "  → https://render.com 방문"
echo "  → GitHub 계정으로 로그인"
echo ""
echo "Step 2: 새 Web Service 생성"
echo "  → 'New +' 버튼 클릭"
echo "  → 'Web Service' 선택"
echo "  → GitHub 리포지토리 연결"
echo ""
echo "Step 3: 기본 설정"
echo "  Name: asknu-backend"
echo "  Region: Singapore (또는 Oregon)"
echo "  Branch: $(git branch --show-current)"
echo "  Runtime: Python 3"
echo "  Build Command: pip install -r requirements.txt"
echo "  Start Command: uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "Step 4: 환경 변수 설정 (Environment 탭)"
echo "======================================"
echo "  다음 환경 변수를 추가하세요:"
echo ""
echo "  DATABASE_URL (필수)"
echo "  값: $(grep DATABASE_URL .env 2>/dev/null | cut -d'=' -f2-)"
echo ""
echo "  UPSTAGE_API_KEY (필수)"
echo "  값: $(grep UPSTAGE_API_KEY .env 2>/dev/null | cut -d'=' -f2-)"
echo ""
echo "  UPSTAGE_MODEL"
echo "  값: solar-pro"
echo ""
echo "  BASE_BOARD"
echo "  값: https://cse.knu.ac.kr/bbs/board.php?bo_table=sub5_1&lang=kor"
echo ""
echo "======================================"
echo ""
echo "Step 5: 플랜 선택"
echo "  ⭕ Free Plan (무료, 슬립 모드 있음)"
echo "  ⭕ Starter Plan ($7/월, 항상 활성)"
echo ""
echo "Step 6: Deploy 버튼 클릭!"
echo "  → 자동 배포 시작"
echo "  → 로그 실시간 확인 가능"
echo "  → 완료되면 URL 생성"
echo ""
echo "======================================"
echo "🎉 배포 완료 후 테스트"
echo "======================================"
echo ""
echo "1. 헬스체크:"
echo "   curl https://your-app.onrender.com/health"
echo ""
echo "2. API 문서:"
echo "   https://your-app.onrender.com/docs"
echo ""
echo "3. 챗봇 테스트:"
echo "   curl -X POST https://your-app.onrender.com/chat \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"question\": \"경진대회 알려줘\"}'"
echo ""
echo "======================================"
echo "📚 상세 가이드: DEPLOYMENT.md"
echo "🆘 문제 발생시: Render 대시보드 Logs 확인"
echo "======================================"
echo ""
echo "✨ 배포 성공을 기원합니다! 🚀"
